### ISSUE TITLE
use referer mod with python and selenium webdriver

### ISSUE THREAD

**Issue by mhndm** [airtower-luna/referer-mod#10]
i can import the addon :
```
fp = webdriver.FirefoxProfile()
path_modify_header = '/path-to/referer-mod.xpi'
fp.add_extension(path_modify_header)
```

what i should enter in the 
`fp.set_preference(???)`

**Comment by airtower-luna** [comment]
I'm not familiar with selenium so can't give an exact answer, but from a quick web search it seems like `fp.set_preference` would set Firefox preferences like those in `about:config`.

Referer-mod doesn't use browser settings, it stores its configuration using the [storage API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage) in the `browser.storage.sync` area. The content of that storage matches what you can export from the add-on preferences page, with the three main objects `same`, `any`, and `domains`.

Does that help?

**Comment by airtower-luna** [comment]
Closing this because there haven't been further questions, feel free to reopen if there are any.
