### ISSUE TITLE
Add a button to the panel

### ISSUE THREAD

**Issue by wvxwxvw** [airtower-luna/referer-mod#11]
How is that? No button. To add a new rule, I have to go to about:addons.

**Comment by airtower-luna** [comment]
I just didn't have the need for a button so far, but I'd be happy to accept a patch that adds one.

**Comment by wvxwxvw** [comment]
See examples in other extensions. I don't write extensions, how do I know? Absolutely most extensions have buttons, so you won't have to go far for examples.

**Comment by anewuser** [comment]
An example of something useful a button could do is enabling/disabling the extension quickly without having to go to the Add-ons Manager. By having to manually open that page to disable the extension, users might forget to re-enable it afterwards.

**Comment by wvxwxvw** [comment]
@airtower-luna 
But the switch never showed up? Thanks for the setup, but you need to do everything.
I don't need to go into settings and look there to find what's not working for me if I'm not sure if it's the extension that's the culprit. I need to disable the extension, make sure it's to blame, and only then dig into the rules.

**Comment by airtower-luna** [comment]
The current release has a toolbar button to open the settings. If you want to have a button that lets you toggle the modifications wait for the next release, see #41.

And if you want to comment more, be more respectful and don't write like I owe you anything.

**Comment by wvxwxvw** [comment]
@airtower-luna 
I'm sorry, I don't speak English very well.
I don't see how to open the extension settings in one click.

**Comment by airtower-luna** [comment]
If you update to 0.11.1 (from yesterday) you should see a button in the toolbar like this, the one between Pocket and the menu:

![grafik](https://user-images.githubusercontent.com/5814919/149035918-3dfb251b-c21e-4e68-a35d-a97977152724.png)

And if you click on it, there's a menu that lets you open settings or disable/enable the add-on.

![grafik](https://user-images.githubusercontent.com/5814919/149036319-d69c1471-c494-40f2-a078-dd41366959d7.png)

I hope that helps! :slightly_smiling_face:

**Comment by wvxwxvw** [comment]
@airtower-luna 
ОК :) 
Now everything is fine.

**Comment by airtower-luna** [comment]
@wvxwxvw I'm glad to hear it works now! :slightly_smiling_face:
