### ISSUE TITLE
Help setting referrer different fron the target url

### ISSUE THREAD

**Issue by shorewall** [airtower-luna/referer-mod#118]
Hi,
Firts apologise for my stupid question, but I'm attempting to develop an mpd player based on local ltml5 players template.
some time I need to bypass the nasty 403 error code by passing a specific referer.
Your addon looks great and can help me to overcome my current lock.
Not always the required refer matches the target url. sometime it is different.
As in this case:
This link: https://lb17.canaletv.live/BalcanMusicTv/index.m3u8
requires this referrer: https://tvonline123.com/
And so many other urls.
I configured the addon as in the attached screenshot to make it works.
How can i config it to use the addon on target site basis?
I've adding a rule for this specific site but I get 403 code if the same referer is not set into the any domain box.
I expected that is a specific rule has been set this rule overrides all the previous rules.
I checked any option into the any domai box but it works only filling by the required referer.
As shown into the attached screenshot.

![Screenshot_20231110_142149](https://github.com/airtower-luna/referer-mod/assets/15981554/644eb5e4-8d58-4c99-8155-febb8fc13d2b)

**Comment by airtower-luna** [comment]
The target and origin domain fields need to contain *only* the domain, not a URL. So in your case the target domain would be `lb17.canaletv.live`.

If you want the rule to apply to every request to that domain (and from your description you do), leave the origin domain field empty.

**Comment by shorewall** [comment]
Thanks very much. I was misleading the addon specs.
Now it works as expected.
Have a nice day

**Comment by shorewall** [comment]
Solved. My congif mistakes...

**Comment by airtower-luna** [comment]
Glad it works now! :smiley_cat:
