### ISSUE TITLE
Add an option to override/remove only 3rd-party referrers for sites

### ISSUE THREAD

**Issue by alexolog** [airtower-luna/referer-mod#12]
The old RefControl add-on allowed for overriding/removing only 3rd-party referrers for a site.

![Untitled](https://user-images.githubusercontent.com/2112513/87098284-f09a4d00-c214-11ea-9a20-61d0f457455f.png)

**Comment by airtower-luna** [comment]
I have been thinking I'd make sense to have rules that match target and unmodified Referer. That would be a more generic solution.

**Comment by teo265** [comment]
> Tiện ích bổ sung RefControl cũ chỉ được phép ghi đè / xóa các liên kết giới thiệu của bên thứ 3 cho một trang web.
> 
> ![Không có tiêu đề](https://user-images.githubusercontent.com/2112513/87098284-f09a4d00-c214-11ea-9a20-61d0f457455f.png)

Good

**Comment by airtower-luna** [comment]
A negative match of the target pattern with the origin might be an implementation option. That is, apply rule if target pattern
* matches target (as usual), and
* original `Referer` doesn't match target pattern.
