### ISSUE TITLE
FR: Allow specifying a source

### ISSUE THREAD

**Issue by Gitoffthelawn** [airtower-luna/referer-mod#15]
Currently, users can specify a target domain to specify a referer.

It would be very useful to also be able to specify a source domain.

A common use for this is when a site requires complete referers (entire URL) within itself (often for API calls), but the user doesn't want to share external referers when clicking on a link to the site.

**Comment by airtower-luna** [comment]
This is something I definitely want, and it'd also resolve #12. I feel the options page needs a rework to make this kind of thing usable, though.

**Comment by Gitoffthelawn** [comment]
Sounds good.  I can help you with the options page design, if you like.

**Comment by airtower-luna** [comment]
That help would be very welcome! :slightly_smiling_face: There are some notes on my thoughts so far in #9.

Another question: How would you prioritize the target and source matching? I'm thinking of best target match first, and looking that the source only after if there are multiple rules for the target.

**Comment by Gitoffthelawn** [comment]
> Another question: How would you prioritize the target and source matching? I'm thinking of best target match first, and looking that the source only after if there are multiple rules for the target.

I had to think about that a bit.

I initially thought to match both target and source, and use whichever is the most restrictive (least amount of `referer` data sent).  That way, the user is *never* sending more than expected.  For conflicts, use the target match.

But after spending more time thinking about it, I think exactly what you wrote is best.  Match the target first, then look at the source only if there are multiple target rule matches.  This way, the user is *never* sending more to a specific target than expected ***and*** can control what gets sent to a target.

Another methodology would be to allow the user to *order* rules, and then:

- apply rules in order, and the ***last*** one to match changes the `referer`
- apply rules in order, and the ***first*** one to match changes the `refer` *and* ends rule processing

My goal is to be as flexible as possible, without introducing complexity that will likely result in errors or unexpected results.

I welcome your thoughts and feedback!

**Comment by airtower-luna** [comment]
Implementation WIP is in #68, tests and comments would be welcome! :smiley_cat:

**Comment by Gitoffthelawn** [comment]
Exciting! 👍🏾
