### ISSUE TITLE
Default SAME rule doesn't keep referers for subdomains

### ISSUE THREAD

**Issue by anewuser** [airtower-luna/referer-mod#28]
Shouldn't the default `SAME → keep` rule include subdomains? I had to whitelist some manually, for example:

`api.imgur.com` → replace → https://imgur.com/upload

Referer Modifier 0.9
Firefox 92

**Comment by airtower-luna** [comment]
That behavior is as intended, the `SAME` rule is meant to cover requests within *exactly* the same domain. For example a request from `api.imgur.com` to an `api.imgur.com` resource is supposed to match, one to `imgur.com` is not.

**Comment by anewuser** [comment]
What benefit do you see in that? I find it counter-productive not to have a way to whitelist all subdomains by default because the current behavior breaks too many sites. Can you consider adding a generic <SUBDOMAINS> rule?
