### ISSUE TITLE
Popup window settings are broken with this addon

### ISSUE THREAD

**Issue by byzod** [airtower-luna/referer-mod#31]
Popup window settings in vanilla firefox no longer works with this addon, please fix it

### Reproduce
1. Install referer modifier
2. Open `demo.html`
3. Click `option` > `Allow popup window` when firefox block the popup window
4. Close tab of `demo.html`
5. Open `demo.html` again

### Expect
`demo.html` opens a new window (or tab) of [amo](https://addons.mozilla.org/zh-CN/firefox/) automatically

### Actual
Firefox block the popup window and the first entry of `option` is `Prevent popup window` instead of allowing it. Click it and nothing happened, [amo](https://addons.mozilla.org/zh-CN/firefox/) popup still failed to open

### Attachment
[demo.zip](https://github.com/airtower-luna/referer-mod/files/7276021/demo.zip)

```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>Popup Demo</title>
</head>
<body>
	<script>
		window.open("https://addons.mozilla.org/firefox/")
	</script>
</body>
</html>
```

**Comment by airtower-luna** [comment]
It works for me (Firefox 92.0). Both "show blocked popup" and allowing popups and then reloading the HTML show me the popup. If it still doesn't work for you please provide additional details how to reproduce the problem: Where is the file loaded from, what other add-ons are active, what does the browser console say, anything else that may be relevant.

**Comment by byzod** [comment]
> Close tab of demo.html
> Open demo.html again

NOT `reloading the HTML`

Did you follow the reproduce step by step?

**Comment by airtower-luna** [comment]
With closing and reopening the tab the pop-up indeed does not appear. However, that behavior stays the same even with referer-mod disabled.

**Comment by byzod** [comment]
Firefox works as expected on [93b9](https://ftp.mozilla.org/pub/devedition/candidates/93.0b9-candidates/build1/)

Reproducable with pure new profile, 0 addon. Please update your firefox and test with a fresh profile.
