### ISSUE TITLE
Add referrer headers (replace setting)

### ISSUE THREAD

**Issue by Joel889** [airtower-luna/referer-mod#4]
The addon page states the following:
> Referer Modifier does not add Referer headers, it only modifies or removes existing ones.

IMHO, when running "replace", then that referrer should always be sent. There could always be a global setting or a checkbox next to the rule indicating whether a referrer header should always be sent.

That's how RefControl used to work.

I'm currently using [Referer Control](https://addons.mozilla.org/en-US/firefox/addon/referercontrol/reviews/), which has that functionality but isn't maintained and has all sorts of other issues.

Unfortunately, since Firefox switched to the new addon system, yours and the other addons I mentioned is all that is left.

Thank you for all your efforts.

**Comment by airtower-luna** [comment]
Please test version 0.7 and let me know if it works as expected!
