### ISSUE TITLE
Secondary/tertiary hosts (AKA sub-subdomains) do not seem to follow rules for subdomains

### ISSUE THREAD

**Issue by Gitoffthelawn** [airtower-luna/referer-mod#40]
I'm not sure if this is a bug or intentional, but secondary/tertiary hosts (e.g. `this.that.example.com`) do not seem to follow the `referer` rules being applied to the corresponding subdomain targets (e.g. `that.example.com`).

You can work around this with regex, but the lack of matching likely will violate user expectations because a target specifier of  `example.com` will match `that.example.com`.

Please note that I have not 100% verified this issue.  I discovered it while working on a real-world scenario, but I don't currently have a web server I can quickly configure for testing.

**Comment by airtower-luna** [comment]
If you can confirm this it's definitely a bug. The intention is that non-regexp rules apply to the given domain and all subdomains, unless a more specific rule (longest matched string from the end of the target domain) overrides it.

**Comment by airtower-luna** [comment]
I just tested by adding `a.b.y.test` to the test environment, and a rule for `y.test` applied to all of `www.y.test`, `site.y.test`, and `a.b.y.test`. If it still occurs for you please share the config you use.

**Comment by Gitoffthelawn** [comment]
In your test environment, does a rule for `b.y.test` get applied to `a.b.y.test`?

BTW, when this came up for me, I was creating rules with `prune` and `keep` attributes.

**Comment by airtower-luna** [comment]
It does. I wonder if [referrer policy](https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns) and similar set by the site might be messing with your test? Prune and keep rules work based on the Referer the browser would send on its own, if that's already origin only (equivalent to prune) or none at all it'll stay that way.

**Comment by Gitoffthelawn** [comment]
> It does. I wonder if [referrer policy](https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns) and similar set by the site might be messing with your test? Prune and keep rules work based on the Referer the browser would send on its own, if that's already origin only (equivalent to prune) or none at all it'll stay that way.

Thanks.  I'll try to take a closer look when (if?) I have a chunk of free time.  I solved that particular referer issue by using `prune` for `y.test` (using your example).  But using `prune` for `b.y.test` didn't work.  I can't include all the details right now, so I'm not sure if that helps figure out what was happening, but if it does, I'm all ears.

Given your test, I have a strong hunch it's not an issue with this extension.  As such, I'm closing this issue, but still be watching it so I can read any thoughts you want to share.
