### ISSUE TITLE
Could you add wildcards and regular expression matches?

### ISSUE THREAD

**Issue by BugFeedback** [airtower-luna/referer-mod#6]
It would be much more convenient to match wildcards and regular expressions, and some subdomains don’t require a lot of input.
You can refer to this extended feature, https://addons.mozilla.org/en-US/firefox/addon/referer-modifier/

**Comment by airtower-luna** [comment]
I'd be open to adding regular expression support, yes. It'd require restructuring the current match logic though, which currently uses the action for the longest matching domain (see [`function findHostConf()` in background.js](https://github.com/airtower-luna/referer-mod/blob/f281051baf4d6a45ae1dc48dffb758ba1189d1ad/background.js#L44)).

To consider:
* Longest regexp match may be a relatively simple alternative.
* Should regular expressions be required to include the end of string (`$`)? There's no technical need to, but leaving it out would mess with match length and may cause unintended matches.
